-- Fix Samuel Jimenez predictions from Excel sheet "Samuel Jimenez"
-- Source: Polla Mundial 2026 1 (1).xlsx
-- Generated on 2026-06-11. Ready to paste in Supabase SQL Editor.

BEGIN;

DELETE FROM predictions WHERE participant_id = 2;
DELETE FROM group_predictions WHERE participant_id = 2;
DELETE FROM individual_predictions WHERE participant_id = 2;

INSERT INTO predictions (participant_id, match_id, predicted_home_goals, predicted_away_goals, predicted_home_team, predicted_away_team, stage) VALUES
  (2, 'G-A-1', 2, 1, 'México', 'Sudáfrica', 'group'),
  (2, 'G-A-2', 1, 0, 'Corea', 'Chequia', 'group'),
  (2, 'G-A-3', 0, 1, 'Sudáfrica', 'Chequia', 'group'),
  (2, 'G-A-4', 1, 0, 'México', 'Corea', 'group'),
  (2, 'G-A-5', 1, 3, 'Chequia', 'México', 'group'),
  (2, 'G-A-6', 0, 2, 'Sudáfrica', 'Corea', 'group'),
  (2, 'G-B-1', 2, 0, 'Canadá', 'Bosnia', 'group'),
  (2, 'G-B-2', 0, 3, 'Catar', 'Suiza', 'group'),
  (2, 'G-B-3', 2, 0, 'Suiza', 'Bosnia', 'group'),
  (2, 'G-B-4', 4, 1, 'Canadá', 'Catar', 'group'),
  (2, 'G-B-5', 1, 1, 'Suiza', 'Canadá', 'group'),
  (2, 'G-B-6', 0, 0, 'Bosnia', 'Catar', 'group'),
  (2, 'G-C-1', 2, 0, 'Brasil', 'Marruecos', 'group'),
  (2, 'G-C-2', 1, 3, 'Haití', 'Escocia', 'group'),
  (2, 'G-C-3', 5, 1, 'Brasil', 'Haití', 'group'),
  (2, 'G-C-4', 0, 1, 'Escocia', 'Marruecos', 'group'),
  (2, 'G-C-5', 0, 2, 'Escocia', 'Brasil', 'group'),
  (2, 'G-C-6', 3, 1, 'Marruecos', 'Haití', 'group'),
  (2, 'G-D-1', 2, 1, 'USA', 'Paraguay', 'group'),
  (2, 'G-D-2', 1, 1, 'Australia', 'Turquía', 'group'),
  (2, 'G-D-3', 3, 1, 'Turquía', 'Paraguay', 'group'),
  (2, 'G-D-4', 1, 3, 'USA', 'Australia', 'group'),
  (2, 'G-D-5', 2, 1, 'Turquía', 'USA', 'group'),
  (2, 'G-D-6', 2, 4, 'Paraguay', 'Australia', 'group'),
  (2, 'G-E-1', 4, 0, 'Alemania', 'Curazao', 'group'),
  (2, 'G-E-2', 2, 5, 'Costa Marfil', 'Ecuador', 'group'),
  (2, 'G-E-3', 3, 1, 'Alemania', 'Costa Marfil', 'group'),
  (2, 'G-E-4', 2, 0, 'Ecuador', 'Curazao', 'group'),
  (2, 'G-E-5', 1, 1, 'Ecuador', 'Alemania', 'group'),
  (2, 'G-E-6', 0, 2, 'Curazao', 'Costa Marfil', 'group'),
  (2, 'G-F-1', 2, 0, 'Holanda', 'Japón', 'group'),
  (2, 'G-F-2', 3, 1, 'Suecia', 'Túnez', 'group'),
  (2, 'G-F-3', 2, 1, 'Holanda', 'Suecia', 'group'),
  (2, 'G-F-4', 2, 3, 'Túnez', 'Japón', 'group'),
  (2, 'G-F-5', 0, 2, 'Japón', 'Suecia', 'group'),
  (2, 'G-F-6', 1, 3, 'Túnez', 'Holanda', 'group'),
  (2, 'G-G-1', 1, 0, 'Irán', 'N. Zelanda', 'group'),
  (2, 'G-G-2', 2, 0, 'Bélgica', 'Egipto', 'group'),
  (2, 'G-G-3', 3, 1, 'Bélgica', 'Irán', 'group'),
  (2, 'G-G-4', 0, 1, 'N. Zelanda', 'Egipto', 'group'),
  (2, 'G-G-5', 0, 3, 'N. Zelanda', 'Bélgica', 'group'),
  (2, 'G-G-6', 3, 2, 'Egipto', 'Irán', 'group'),
  (2, 'G-H-1', 5, 1, 'España', 'Cabo Verde', 'group'),
  (2, 'G-H-2', 2, 4, 'A. Saudita', 'Uruguay', 'group'),
  (2, 'G-H-3', 2, 0, 'España', 'A. Saudita', 'group'),
  (2, 'G-H-4', 2, 0, 'Uruguay', 'Cabo Verde', 'group'),
  (2, 'G-H-5', 1, 3, 'Uruguay', 'España', 'group'),
  (2, 'G-H-6', 1, 2, 'Cabo Verde', 'A. Saudita', 'group'),
  (2, 'G-I-1', 2, 1, 'Francia', 'Senegal', 'group'),
  (2, 'G-I-2', 0, 2, 'Irak', 'Noruega', 'group'),
  (2, 'G-I-3', 3, 0, 'Francia', 'Irak', 'group'),
  (2, 'G-I-4', 2, 2, 'Noruega', 'Senegal', 'group'),
  (2, 'G-I-5', 2, 4, 'Noruega', 'Francia', 'group'),
  (2, 'G-I-6', 2, 0, 'Senegal', 'Irak', 'group'),
  (2, 'G-J-1', 4, 1, 'Argentina', 'Argelia', 'group'),
  (2, 'G-J-2', 2, 0, 'Austria', 'Jordania', 'group'),
  (2, 'G-J-3', 2, 0, 'Argentina', 'Austria', 'group'),
  (2, 'G-J-4', 1, 3, 'Jordania', 'Argelia', 'group'),
  (2, 'G-J-5', 1, 2, 'Jordania', 'Argentina', 'group'),
  (2, 'G-J-6', 1, 1, 'Argelia', 'Austria', 'group'),
  (2, 'G-K-1', 3, 0, 'Portugal', 'RD Congo', 'group'),
  (2, 'G-K-2', 1, 4, 'Uzbekistán', 'Colombia', 'group'),
  (2, 'G-K-3', 2, 0, 'Portugal', 'Uzbekistán', 'group'),
  (2, 'G-K-4', 2, 0, 'Colombia', 'RD Congo', 'group'),
  (2, 'G-K-5', 2, 2, 'Colombia', 'Portugal', 'group'),
  (2, 'G-K-6', 0, 1, 'RD Congo', 'Uzbekistán', 'group'),
  (2, 'G-L-1', 2, 0, 'Inglaterra', 'Croacia', 'group'),
  (2, 'G-L-2', 1, 1, 'Ghana', 'Panamá', 'group'),
  (2, 'G-L-3', 3, 1, 'Inglaterra', 'Ghana', 'group'),
  (2, 'G-L-4', 0, 2, 'Panamá', 'Croacia', 'group'),
  (2, 'G-L-5', 0, 3, 'Panamá', 'Inglaterra', 'group'),
  (2, 'G-L-6', 1, 0, 'Croacia', 'Ghana', 'group'),
  (2, 'M1', 2, 0, 'Alemania', 'Sudáfrica', 'r32'),
  (2, 'M9', 3, 2, 'Brasil', 'Suecia', 'r32'),
  (2, 'O1', 1, 3, 'Alemania', 'Francia', 'r16'),
  (2, 'M2', 6, 2, 'Francia', 'Irán', 'r32'),
  (2, 'M10', 2, 1, 'Ecuador', 'Senegal', 'r32'),
  (2, 'O2', 0, 1, 'Suiza', 'Holanda', 'r16'),
  (2, 'M3', 0, 1, 'Corea', 'Suiza', 'r32'),
  (2, 'M11', 3, 1, 'México', 'Costa Marfil', 'r32'),
  (2, 'O3', 3, 2, 'Portugal', 'España', 'r16'),
  (2, 'M4', 3, 1, 'Holanda', 'Marruecos', 'r32'),
  (2, 'M12', 3, 0, 'Inglaterra', 'Argelia', 'r32'),
  (2, 'O4', 1, 2, 'Noruega', 'Bélgica', 'r16'),
  (2, 'M5', 3, 1, 'Portugal', 'Croacia', 'r32'),
  (2, 'M13', 3, 1, 'Argentina', 'Uruguay', 'r32'),
  (2, 'O5', 2, 0, 'Brasil', 'Senegal', 'r16'),
  (2, 'M6', 4, 0, 'España', 'Austria', 'r32'),
  (2, 'M14', 2, 0, 'Turquía', 'Egipto', 'r32'),
  (2, 'O6', 1, 3, 'México', 'Inglaterra', 'r16'),
  (2, 'M7', 0, 2, 'Australia', 'Noruega', 'r32'),
  (2, 'M15', 2, 1, 'Canadá', 'Escocia', 'r32'),
  (2, 'O7', 4, 1, 'Argentina', 'Turquía', 'r16'),
  (2, 'M8', 3, 1, 'Bélgica', 'A. Saudita', 'r32'),
  (2, 'M16', 4, 1, 'Colombia', 'USA', 'r32'),
  (2, 'O8', 0, 2, 'Canadá', 'Colombia', 'r16'),
  (2, 'Q1', 2, 0, 'Francia', 'Holanda', 'qf'),
  (2, 'Q2', 1, 0, 'Portugal', 'Bélgica', 'qf'),
  (2, 'Q3', 2, 3, 'Brasil', 'Inglaterra', 'qf'),
  (2, 'Q4', 1, 2, 'Argentina', 'Colombia', 'qf'),
  (2, 'S1', 1, 2, 'Francia', 'Portugal', 'sf'),
  (2, 'S2', 3, 3, 'Inglaterra', 'Colombia', 'sf'),
  (2, 'FINAL', 3, 2, 'Portugal', 'Inglaterra', 'final'),
  (2, 'THIRD', 3, 1, 'Francia', 'Colombia', 'third');

INSERT INTO group_predictions (participant_id, group_code, team_code, predicted_position) VALUES
  (2, 'A', 'México', 1),
  (2, 'A', 'Corea', 2),
  (2, 'A', 'Sudáfrica', 3),
  (2, 'A', 'Chequia', 4),
  (2, 'B', 'Canadá', 1),
  (2, 'B', 'Suiza', 2),
  (2, 'B', 'Bosnia', 3),
  (2, 'B', 'Catar', 4),
  (2, 'C', 'Brasil', 1),
  (2, 'C', 'Marruecos', 2),
  (2, 'C', 'Escocia', 3),
  (2, 'C', 'Haití', 4),
  (2, 'D', 'Australia', 1),
  (2, 'D', 'Turquía', 2),
  (2, 'D', 'USA', 3),
  (2, 'D', 'Paraguay', 4),
  (2, 'E', 'Alemania', 1),
  (2, 'E', 'Ecuador', 2),
  (2, 'E', 'Costa Marfil', 3),
  (2, 'E', 'Curazao', 4),
  (2, 'F', 'Holanda', 1),
  (2, 'F', 'Suecia', 2),
  (2, 'F', 'Japón', 3),
  (2, 'F', 'Túnez', 4),
  (2, 'G', 'Bélgica', 1),
  (2, 'G', 'Egipto', 2),
  (2, 'G', 'Irán', 3),
  (2, 'G', 'N. Zelanda', 4),
  (2, 'H', 'España', 1),
  (2, 'H', 'Uruguay', 2),
  (2, 'H', 'A. Saudita', 3),
  (2, 'H', 'Cabo Verde', 4),
  (2, 'I', 'Francia', 1),
  (2, 'I', 'Senegal', 2),
  (2, 'I', 'Noruega', 3),
  (2, 'I', 'Irak', 4),
  (2, 'J', 'Argentina', 1),
  (2, 'J', 'Austria', 2),
  (2, 'J', 'Argelia', 3),
  (2, 'J', 'Jordania', 4),
  (2, 'K', 'Colombia', 1),
  (2, 'K', 'Portugal', 2),
  (2, 'K', 'Uzbekistán', 3),
  (2, 'K', 'RD Congo', 4),
  (2, 'L', 'Inglaterra', 1),
  (2, 'L', 'Croacia', 2),
  (2, 'L', 'Ghana', 3),
  (2, 'L', 'Panamá', 4);

INSERT INTO individual_predictions (participant_id, top_scorer, best_player, best_goalkeeper) VALUES
  (2, 'Mbappé', 'Vitinha', 'Diogo Costa');

COMMIT;

-- Verification
SELECT COUNT(*) AS samuel_predictions
FROM predictions
WHERE participant_id = 2;

SELECT participant_id, top_scorer, best_player, best_goalkeeper
FROM individual_predictions
WHERE participant_id = 2;
